### ISSUE TITLE
Remove feature_base from 3to2

### ISSUE THREAD

**Issue by ryanwersal** [ryanwersal/crosswind#17]
We're dropping support for Python versions below 2.7 so it is no longer needed. It appears to have been used to provide warnings for features that couldn't be converted.

**Comment by ghost** [comment]
I'll try this out, if it's fine

**Comment by ryanwersal** [comment]
Sure! There's a few pending changes I haven't quite landed yet (the work for #6 and friends) but I don't think the conflicts will be difficult to resolve since this change should be isolated to the tests directory in lib3to2. Feel free to ask questions on here and we can discuss. Good luck!

**Comment by ghost** [comment]
Accidentally forgot to make a new branch before making the changes. Will just be done in a bit
