### ISSUE TITLE
Add standarderror fixer in 3to2

### ISSUE THREAD

**Issue by ryanwersal** [ryanwersal/crosswind#43]
`StandardError` and `Exception` aren't the same thing so we will need to add a fixer for it in 3to2 to mirror the 2to3 fixer.

**Comment by ghost** [comment]
I'm curious what your thoughts are on this one's implementation. It seems like it would be hard to determine what should utilize StandardError once all instances of it were replaced with Exception in python 3.

**Comment by ryanwersal** [comment]
After doing some more reading of the exception documentation for both [Python 2.7](https://docs.python.org/2/library/exceptions.html) and [Python 3.6](https://docs.python.org/3.6/library/exceptions.html) I think I'm of a similar mind. There probably isn't much motivation for trying to change any given `Exception` into `StandardError` even presuming we have a good means of telling when we should use each.

I think I'll close this and update the wiki to indicate that there is no need for this fixer.
